// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { GetApiSettingsData, GetApiSettingsErrors, GetApiSettingsResponses, GetGeneralSettingsData, GetGeneralSettingsErrors, GetGeneralSettingsResponses, GetNotificationSettingsData, GetNotificationSettingsErrors, GetNotificationSettingsResponses, GetSettingsData, GetSettingsErrors, GetSettingsResponses, UpdateApiSettingsData, UpdateApiSettingsErrors, UpdateApiSettingsResponses, UpdateGeneralSettingsData, UpdateGeneralSettingsErrors, UpdateGeneralSettingsResponses, UpdateNotificationSettingsData, UpdateNotificationSettingsErrors, UpdateNotificationSettingsResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Obtener todas las configuraciones
 */
export const getSettings = <ThrowOnError extends boolean = false>(options?: Options<GetSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetSettingsResponses, GetSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/settings',
    ...options
});

/**
 * Obtener configuración general
 */
export const getGeneralSettings = <ThrowOnError extends boolean = false>(options?: Options<GetGeneralSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetGeneralSettingsResponses, GetGeneralSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/settings/general',
    ...options
});

/**
 * Actualizar configuración general
 */
export const updateGeneralSettings = <ThrowOnError extends boolean = false>(options: Options<UpdateGeneralSettingsData, ThrowOnError>) => (options.client ?? client).patch<UpdateGeneralSettingsResponses, UpdateGeneralSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/settings/general',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Obtener configuración de la API
 */
export const getApiSettings = <ThrowOnError extends boolean = false>(options?: Options<GetApiSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetApiSettingsResponses, GetApiSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/settings/api',
    ...options
});

/**
 * Actualizar configuración de la API
 */
export const updateApiSettings = <ThrowOnError extends boolean = false>(options: Options<UpdateApiSettingsData, ThrowOnError>) => (options.client ?? client).patch<UpdateApiSettingsResponses, UpdateApiSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/settings/api',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Obtener preferencias de notificaciones
 */
export const getNotificationSettings = <ThrowOnError extends boolean = false>(options?: Options<GetNotificationSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetNotificationSettingsResponses, GetNotificationSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/settings/notifications',
    ...options
});

/**
 * Actualizar preferencias de notificaciones
 */
export const updateNotificationSettings = <ThrowOnError extends boolean = false>(options: Options<UpdateNotificationSettingsData, ThrowOnError>) => (options.client ?? client).patch<UpdateNotificationSettingsResponses, UpdateNotificationSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/settings/notifications',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
