// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000/api' | (string & {});
};

export type GeneralSettings = {
    /**
     * Nombre de la aplicación
     */
    applicationName: string;
    /**
     * Entorno activo de la aplicación
     */
    environment: 'development' | 'staging' | 'production';
    /**
     * Zona horaria en formato IANA (ej. Europe/Madrid)
     */
    timezone: string;
};

export type ApiSettings = {
    /**
     * URL base del backend al que apunta el frontend
     */
    apiBaseUrl: string;
    /**
     * Tiempo máximo de espera para llamadas HTTP en milisegundos
     */
    apiTimeoutMs: number;
    /**
     * Habilitar caché de respuestas de la API
     */
    enableApiCaching: boolean;
};

export type NotificationSettings = {
    /**
     * Enviar email cuando un comando finaliza exitosamente
     */
    emailOnCommandCompletion: boolean;
    /**
     * Enviar notificación push cuando un comando falla
     */
    pushOnError: boolean;
    /**
     * Enviar resumen semanal de actividad por email
     */
    weeklySummaryEnabled: boolean;
};

export type SettingsResponse = {
    general: GeneralSettings;
    api: ApiSettings;
    notifications: NotificationSettings;
};

export type Error = {
    /**
     * Código de error
     */
    error: string;
    /**
     * Mensaje descriptivo
     */
    message: string;
    /**
     * Detalles adicionales del error
     */
    details?: {
        [key: string]: unknown;
    };
};

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings';
};

export type GetSettingsErrors = {
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Error interno del servidor
     */
    500: Error;
};

export type GetSettingsError = GetSettingsErrors[keyof GetSettingsErrors];

export type GetSettingsResponses = {
    /**
     * Configuración completa de la aplicación
     */
    200: SettingsResponse;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type GetGeneralSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/general';
};

export type GetGeneralSettingsErrors = {
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Error interno del servidor
     */
    500: Error;
};

export type GetGeneralSettingsError = GetGeneralSettingsErrors[keyof GetGeneralSettingsErrors];

export type GetGeneralSettingsResponses = {
    /**
     * Configuración general
     */
    200: GeneralSettings;
};

export type GetGeneralSettingsResponse = GetGeneralSettingsResponses[keyof GetGeneralSettingsResponses];

export type UpdateGeneralSettingsData = {
    body: GeneralSettings;
    path?: never;
    query?: never;
    url: '/settings/general';
};

export type UpdateGeneralSettingsErrors = {
    /**
     * Solicitud inválida
     */
    400: Error;
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Error interno del servidor
     */
    500: Error;
};

export type UpdateGeneralSettingsError = UpdateGeneralSettingsErrors[keyof UpdateGeneralSettingsErrors];

export type UpdateGeneralSettingsResponses = {
    /**
     * Configuración general actualizada
     */
    200: GeneralSettings;
};

export type UpdateGeneralSettingsResponse = UpdateGeneralSettingsResponses[keyof UpdateGeneralSettingsResponses];

export type GetApiSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/api';
};

export type GetApiSettingsErrors = {
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Error interno del servidor
     */
    500: Error;
};

export type GetApiSettingsError = GetApiSettingsErrors[keyof GetApiSettingsErrors];

export type GetApiSettingsResponses = {
    /**
     * Configuración de la API
     */
    200: ApiSettings;
};

export type GetApiSettingsResponse = GetApiSettingsResponses[keyof GetApiSettingsResponses];

export type UpdateApiSettingsData = {
    body: ApiSettings;
    path?: never;
    query?: never;
    url: '/settings/api';
};

export type UpdateApiSettingsErrors = {
    /**
     * Solicitud inválida
     */
    400: Error;
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Error interno del servidor
     */
    500: Error;
};

export type UpdateApiSettingsError = UpdateApiSettingsErrors[keyof UpdateApiSettingsErrors];

export type UpdateApiSettingsResponses = {
    /**
     * Configuración de la API actualizada
     */
    200: ApiSettings;
};

export type UpdateApiSettingsResponse = UpdateApiSettingsResponses[keyof UpdateApiSettingsResponses];

export type GetNotificationSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/notifications';
};

export type GetNotificationSettingsErrors = {
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Error interno del servidor
     */
    500: Error;
};

export type GetNotificationSettingsError = GetNotificationSettingsErrors[keyof GetNotificationSettingsErrors];

export type GetNotificationSettingsResponses = {
    /**
     * Preferencias de notificaciones
     */
    200: NotificationSettings;
};

export type GetNotificationSettingsResponse = GetNotificationSettingsResponses[keyof GetNotificationSettingsResponses];

export type UpdateNotificationSettingsData = {
    body: NotificationSettings;
    path?: never;
    query?: never;
    url: '/settings/notifications';
};

export type UpdateNotificationSettingsErrors = {
    /**
     * Solicitud inválida
     */
    400: Error;
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Error interno del servidor
     */
    500: Error;
};

export type UpdateNotificationSettingsError = UpdateNotificationSettingsErrors[keyof UpdateNotificationSettingsErrors];

export type UpdateNotificationSettingsResponses = {
    /**
     * Preferencias de notificaciones actualizadas
     */
    200: NotificationSettings;
};

export type UpdateNotificationSettingsResponse = UpdateNotificationSettingsResponses[keyof UpdateNotificationSettingsResponses];
