/* tslint:disable */
/* eslint-disable */
/**
 * Command API
 * API para ejecución remota de comandos en el sistema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommandListResponse,
  CommandRequest,
  CommandResponse,
  CommandResult,
} from '../models/index';
import {
    CommandListResponseFromJSON,
    CommandListResponseToJSON,
    CommandRequestFromJSON,
    CommandRequestToJSON,
    CommandResponseFromJSON,
    CommandResponseToJSON,
    CommandResultFromJSON,
    CommandResultToJSON,
} from '../models/index';

export interface ExecuteCommandRequest {
    commandRequest: CommandRequest;
}

export interface GetCommandRequest {
    id: string;
}

export interface GetCommandResultRequest {
    id: string;
}

export interface ListCommandsRequest {
    status?: ListCommandsStatusEnum;
    source?: string;
    limit?: number;
    offset?: number;
}

/**
 * 
 */
export class CommandsApi extends runtime.BaseAPI {

    /**
     * Creates request options for executeCommand without sending the request
     */
    async executeCommandRequestOpts(requestParameters: ExecuteCommandRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commandRequest'] == null) {
            throw new runtime.RequiredError(
                'commandRequest',
                'Required parameter "commandRequest" was null or undefined when calling executeCommand().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/commands`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CommandRequestToJSON(requestParameters['commandRequest']),
        };
    }

    /**
     * Enviar un comando para ejecución
     */
    async executeCommandRaw(requestParameters: ExecuteCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandResponse>> {
        const requestOptions = await this.executeCommandRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandResponseFromJSON(jsonValue));
    }

    /**
     * Enviar un comando para ejecución
     */
    async executeCommand(requestParameters: ExecuteCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandResponse> {
        const response = await this.executeCommandRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommand without sending the request
     */
    async getCommandRequestOpts(requestParameters: GetCommandRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCommand().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/commands/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Consultar estado de un comando
     */
    async getCommandRaw(requestParameters: GetCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandResponse>> {
        const requestOptions = await this.getCommandRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandResponseFromJSON(jsonValue));
    }

    /**
     * Consultar estado de un comando
     */
    async getCommand(requestParameters: GetCommandRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandResponse> {
        const response = await this.getCommandRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommandResult without sending the request
     */
    async getCommandResultRequestOpts(requestParameters: GetCommandResultRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCommandResult().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/commands/{id}/result`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener resultado de un comando
     */
    async getCommandResultRaw(requestParameters: GetCommandResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandResult>> {
        const requestOptions = await this.getCommandResultRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandResultFromJSON(jsonValue));
    }

    /**
     * Obtener resultado de un comando
     */
    async getCommandResult(requestParameters: GetCommandResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandResult> {
        const response = await this.getCommandResultRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCommands without sending the request
     */
    async listCommandsRequestOpts(requestParameters: ListCommandsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['source'] != null) {
            queryParameters['source'] = requestParameters['source'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/commands`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Listar comandos
     */
    async listCommandsRaw(requestParameters: ListCommandsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommandListResponse>> {
        const requestOptions = await this.listCommandsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommandListResponseFromJSON(jsonValue));
    }

    /**
     * Listar comandos
     */
    async listCommands(requestParameters: ListCommandsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommandListResponse> {
        const response = await this.listCommandsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListCommandsStatusEnum = {
    pending: 'pending',
    processing: 'processing',
    completed: 'completed',
    failed: 'failed'
} as const;
export type ListCommandsStatusEnum = typeof ListCommandsStatusEnum[keyof typeof ListCommandsStatusEnum];
