/* tslint:disable */
/* eslint-disable */
/**
 * Command API
 * API para ejecución remota de comandos en el sistema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommandResultData
 */
export interface CommandResultData {
    /**
     * Mensaje del resultado
     * @type {string}
     * @memberof CommandResultData
     */
    message?: string;
    /**
     * Salida del comando
     * @type {string}
     * @memberof CommandResultData
     */
    output?: string;
}

/**
 * Check if a given object implements the CommandResultData interface.
 */
export function instanceOfCommandResultData(value: object): value is CommandResultData {
    return true;
}

export function CommandResultDataFromJSON(json: any): CommandResultData {
    return CommandResultDataFromJSONTyped(json, false);
}

export function CommandResultDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandResultData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'output': json['output'] == null ? undefined : json['output'],
    };
}

export function CommandResultDataToJSON(json: any): CommandResultData {
    return CommandResultDataToJSONTyped(json, false);
}

export function CommandResultDataToJSONTyped(value?: CommandResultData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'output': value['output'],
    };
}

