/* tslint:disable */
/* eslint-disable */
/**
 * Command API
 * API para ejecución remota de comandos en el sistema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommandMetadata } from './CommandMetadata';
import {
    CommandMetadataFromJSON,
    CommandMetadataFromJSONTyped,
    CommandMetadataToJSON,
    CommandMetadataToJSONTyped,
} from './CommandMetadata';
import type { CommandPayload } from './CommandPayload';
import {
    CommandPayloadFromJSON,
    CommandPayloadFromJSONTyped,
    CommandPayloadToJSON,
    CommandPayloadToJSONTyped,
} from './CommandPayload';

/**
 * 
 * @export
 * @interface CommandRequest
 */
export interface CommandRequest {
    /**
     * Nombre del comando a ejecutar
     * @type {string}
     * @memberof CommandRequest
     */
    command: string;
    /**
     * 
     * @type {CommandPayload}
     * @memberof CommandRequest
     */
    payload?: CommandPayload;
    /**
     * 
     * @type {CommandMetadata}
     * @memberof CommandRequest
     */
    metadata?: CommandMetadata;
}

/**
 * Check if a given object implements the CommandRequest interface.
 */
export function instanceOfCommandRequest(value: object): value is CommandRequest {
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function CommandRequestFromJSON(json: any): CommandRequest {
    return CommandRequestFromJSONTyped(json, false);
}

export function CommandRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'command': json['command'],
        'payload': json['payload'] == null ? undefined : CommandPayloadFromJSON(json['payload']),
        'metadata': json['metadata'] == null ? undefined : CommandMetadataFromJSON(json['metadata']),
    };
}

export function CommandRequestToJSON(json: any): CommandRequest {
    return CommandRequestToJSONTyped(json, false);
}

export function CommandRequestToJSONTyped(value?: CommandRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'command': value['command'],
        'payload': CommandPayloadToJSON(value['payload']),
        'metadata': CommandMetadataToJSON(value['metadata']),
    };
}

