/* tslint:disable */
/* eslint-disable */
/**
 * Command API
 * API para ejecución remota de comandos en el sistema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommandResponse } from './CommandResponse';
import {
    CommandResponseFromJSON,
    CommandResponseFromJSONTyped,
    CommandResponseToJSON,
    CommandResponseToJSONTyped,
} from './CommandResponse';

/**
 * 
 * @export
 * @interface CommandListResponse
 */
export interface CommandListResponse {
    /**
     * 
     * @type {Array<CommandResponse>}
     * @memberof CommandListResponse
     */
    items?: Array<CommandResponse>;
    /**
     * 
     * @type {number}
     * @memberof CommandListResponse
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof CommandListResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof CommandListResponse
     */
    offset?: number;
}

/**
 * Check if a given object implements the CommandListResponse interface.
 */
export function instanceOfCommandListResponse(value: object): value is CommandListResponse {
    return true;
}

export function CommandListResponseFromJSON(json: any): CommandListResponse {
    return CommandListResponseFromJSONTyped(json, false);
}

export function CommandListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CommandResponseFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function CommandListResponseToJSON(json: any): CommandListResponse {
    return CommandListResponseToJSONTyped(json, false);
}

export function CommandListResponseToJSONTyped(value?: CommandListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CommandResponseToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

