/* tslint:disable */
/* eslint-disable */
/**
 * Command API
 * API para ejecución remota de comandos en el sistema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommandResultData } from './CommandResultData';
import {
    CommandResultDataFromJSON,
    CommandResultDataFromJSONTyped,
    CommandResultDataToJSON,
    CommandResultDataToJSONTyped,
} from './CommandResultData';

/**
 * 
 * @export
 * @interface CommandResult
 */
export interface CommandResult {
    /**
     * ID único del comando
     * @type {string}
     * @memberof CommandResult
     */
    id?: string;
    /**
     * Estado actual del comando
     * @type {CommandResultStatusEnum}
     * @memberof CommandResult
     */
    status?: CommandResultStatusEnum;
    /**
     * 
     * @type {CommandResultData}
     * @memberof CommandResult
     */
    result?: CommandResultData;
    /**
     * Mensaje de error si falló
     * @type {string}
     * @memberof CommandResult
     */
    error?: string;
    /**
     * Timestamp de completado
     * @type {Date}
     * @memberof CommandResult
     */
    completedAt?: Date;
}


/**
 * @export
 */
export const CommandResultStatusEnum = {
    pending: 'pending',
    processing: 'processing',
    completed: 'completed',
    failed: 'failed'
} as const;
export type CommandResultStatusEnum = typeof CommandResultStatusEnum[keyof typeof CommandResultStatusEnum];


/**
 * Check if a given object implements the CommandResult interface.
 */
export function instanceOfCommandResult(value: object): value is CommandResult {
    return true;
}

export function CommandResultFromJSON(json: any): CommandResult {
    return CommandResultFromJSONTyped(json, false);
}

export function CommandResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
        'result': json['result'] == null ? undefined : CommandResultDataFromJSON(json['result']),
        'error': json['error'] == null ? undefined : json['error'],
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
    };
}

export function CommandResultToJSON(json: any): CommandResult {
    return CommandResultToJSONTyped(json, false);
}

export function CommandResultToJSONTyped(value?: CommandResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'result': CommandResultDataToJSON(value['result']),
        'error': value['error'],
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
    };
}

