/* tslint:disable */
/* eslint-disable */
/**
 * Command API
 * API para ejecución remota de comandos en el sistema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommandResultData } from './CommandResultData';
import {
    CommandResultDataFromJSON,
    CommandResultDataFromJSONTyped,
    CommandResultDataToJSON,
    CommandResultDataToJSONTyped,
} from './CommandResultData';
import type { CommandMetadata } from './CommandMetadata';
import {
    CommandMetadataFromJSON,
    CommandMetadataFromJSONTyped,
    CommandMetadataToJSON,
    CommandMetadataToJSONTyped,
} from './CommandMetadata';
import type { CommandPayload } from './CommandPayload';
import {
    CommandPayloadFromJSON,
    CommandPayloadFromJSONTyped,
    CommandPayloadToJSON,
    CommandPayloadToJSONTyped,
} from './CommandPayload';

/**
 * 
 * @export
 * @interface CommandResponse
 */
export interface CommandResponse {
    /**
     * ID único del comando
     * @type {string}
     * @memberof CommandResponse
     */
    id: string;
    /**
     * Estado actual del comando
     * @type {CommandResponseStatusEnum}
     * @memberof CommandResponse
     */
    status: CommandResponseStatusEnum;
    /**
     * Comando ejecutado
     * @type {string}
     * @memberof CommandResponse
     */
    command: string;
    /**
     * 
     * @type {CommandPayload}
     * @memberof CommandResponse
     */
    payload?: CommandPayload;
    /**
     * 
     * @type {CommandMetadata}
     * @memberof CommandResponse
     */
    metadata?: CommandMetadata;
    /**
     * 
     * @type {CommandResultData}
     * @memberof CommandResponse
     */
    result?: CommandResultData;
    /**
     * Mensaje de error si falló
     * @type {string}
     * @memberof CommandResponse
     */
    error?: string;
    /**
     * Timestamp de creación
     * @type {Date}
     * @memberof CommandResponse
     */
    createdAt: Date;
    /**
     * Timestamp de completado
     * @type {Date}
     * @memberof CommandResponse
     */
    completedAt?: Date;
}


/**
 * @export
 */
export const CommandResponseStatusEnum = {
    pending: 'pending',
    processing: 'processing',
    completed: 'completed',
    failed: 'failed'
} as const;
export type CommandResponseStatusEnum = typeof CommandResponseStatusEnum[keyof typeof CommandResponseStatusEnum];


/**
 * Check if a given object implements the CommandResponse interface.
 */
export function instanceOfCommandResponse(value: object): value is CommandResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('command' in value) || value['command'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CommandResponseFromJSON(json: any): CommandResponse {
    return CommandResponseFromJSONTyped(json, false);
}

export function CommandResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'command': json['command'],
        'payload': json['payload'] == null ? undefined : CommandPayloadFromJSON(json['payload']),
        'metadata': json['metadata'] == null ? undefined : CommandMetadataFromJSON(json['metadata']),
        'result': json['result'] == null ? undefined : CommandResultDataFromJSON(json['result']),
        'error': json['error'] == null ? undefined : json['error'],
        'createdAt': (new Date(json['createdAt'])),
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
    };
}

export function CommandResponseToJSON(json: any): CommandResponse {
    return CommandResponseToJSONTyped(json, false);
}

export function CommandResponseToJSONTyped(value?: CommandResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'command': value['command'],
        'payload': CommandPayloadToJSON(value['payload']),
        'metadata': CommandMetadataToJSON(value['metadata']),
        'result': CommandResultDataToJSON(value['result']),
        'error': value['error'],
        'createdAt': value['createdAt'].toISOString(),
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
    };
}

