/* tslint:disable */
/* eslint-disable */
/**
 * Command API
 * API para ejecución remota de comandos en el sistema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommandPayload
 */
export interface CommandPayload {
    /**
     * Entorno de despliegue
     * @type {string}
     * @memberof CommandPayload
     */
    environment?: string;
    /**
     * Versión a desplegar
     * @type {string}
     * @memberof CommandPayload
     */
    version?: string;
}

/**
 * Check if a given object implements the CommandPayload interface.
 */
export function instanceOfCommandPayload(value: object): value is CommandPayload {
    return true;
}

export function CommandPayloadFromJSON(json: any): CommandPayload {
    return CommandPayloadFromJSONTyped(json, false);
}

export function CommandPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'environment': json['environment'] == null ? undefined : json['environment'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function CommandPayloadToJSON(json: any): CommandPayload {
    return CommandPayloadToJSONTyped(json, false);
}

export function CommandPayloadToJSONTyped(value?: CommandPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'environment': value['environment'],
        'version': value['version'],
    };
}

