/* tslint:disable */
/* eslint-disable */
/**
 * Command API
 * API para ejecución remota de comandos en el sistema
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommandMetadata
 */
export interface CommandMetadata {
    /**
     * Origen del comando
     * @type {string}
     * @memberof CommandMetadata
     */
    source?: string;
    /**
     * ID de correlación
     * @type {string}
     * @memberof CommandMetadata
     */
    correlationId?: string;
}

/**
 * Check if a given object implements the CommandMetadata interface.
 */
export function instanceOfCommandMetadata(value: object): value is CommandMetadata {
    return true;
}

export function CommandMetadataFromJSON(json: any): CommandMetadata {
    return CommandMetadataFromJSONTyped(json, false);
}

export function CommandMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommandMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'] == null ? undefined : json['source'],
        'correlationId': json['correlationId'] == null ? undefined : json['correlationId'],
    };
}

export function CommandMetadataToJSON(json: any): CommandMetadata {
    return CommandMetadataToJSONTyped(json, false);
}

export function CommandMetadataToJSONTyped(value?: CommandMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'correlationId': value['correlationId'],
    };
}

