// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { ExecuteCommandData, ExecuteCommandErrors, ExecuteCommandResponses, GetCommandData, GetCommandErrors, GetCommandResponses, GetCommandResultData, GetCommandResultErrors, GetCommandResultResponses, ListCommandsData, ListCommandsErrors, ListCommandsResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Listar comandos
 */
export const listCommands = <ThrowOnError extends boolean = false>(options?: Options<ListCommandsData, ThrowOnError>) => (options?.client ?? client).get<ListCommandsResponses, ListCommandsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/commands',
    ...options
});

/**
 * Enviar un comando para ejecución
 */
export const executeCommand = <ThrowOnError extends boolean = false>(options: Options<ExecuteCommandData, ThrowOnError>) => (options.client ?? client).post<ExecuteCommandResponses, ExecuteCommandErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/commands',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Consultar estado de un comando
 */
export const getCommand = <ThrowOnError extends boolean = false>(options: Options<GetCommandData, ThrowOnError>) => (options.client ?? client).get<GetCommandResponses, GetCommandErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/commands/{id}',
    ...options
});

/**
 * Obtener resultado de un comando
 */
export const getCommandResult = <ThrowOnError extends boolean = false>(options: Options<GetCommandResultData, ThrowOnError>) => (options.client ?? client).get<GetCommandResultResponses, GetCommandResultErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/commands/{id}/result',
    ...options
});
