// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, Options as Options2, TDataShape } from './client/index.js';
import type { GetDashboardActivityData, GetDashboardActivityErrors, GetDashboardActivityResponses, GetDashboardMetricsData, GetDashboardMetricsErrors, GetDashboardMetricsResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Obtener métricas del sistema
 */
export const getDashboardMetrics = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardMetricsData, ThrowOnError>) => (options?.client ?? client).get<GetDashboardMetricsResponses, GetDashboardMetricsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dashboard/metrics',
    ...options
});

/**
 * Obtener actividad reciente
 */
export const getDashboardActivity = <ThrowOnError extends boolean = false>(options?: Options<GetDashboardActivityData, ThrowOnError>) => (options?.client ?? client).get<GetDashboardActivityResponses, GetDashboardActivityErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dashboard/activity',
    ...options
});
