// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000/api' | (string & {});
};

export type DashboardMetrics = {
    /**
     * Número de comandos pendientes
     */
    pending: number;
    /**
     * Número de comandos en procesamiento
     */
    processing: number;
    /**
     * Número de comandos completados
     */
    completed: number;
    /**
     * Número de comandos fallidos
     */
    failed: number;
};

export type DashboardActivity = Array<ActivityItem>;

export type ActivityItem = {
    /**
     * Identificador único de la actividad
     */
    id: string;
    /**
     * Fecha y hora de la actividad
     */
    timestamp: string;
    /**
     * Tipo de actividad
     */
    type: 'command-start' | 'command-complete' | 'command-error' | 'notification';
    /**
     * Descripción legible de la actividad
     */
    description: string;
    /**
     * ID del usuario asociado (opcional)
     */
    userId?: string;
    /**
     * Metadatos adicionales específicos del tipo de actividad
     */
    metadata?: {
        [key: string]: unknown;
    };
};

export type Error = {
    /**
     * Código de error
     */
    error: string;
    /**
     * Mensaje descriptivo
     */
    message: string;
    /**
     * Detalles adicionales del error
     */
    details?: {
        [key: string]: unknown;
    };
};

export type GetDashboardMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/metrics';
};

export type GetDashboardMetricsErrors = {
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Error interno del servidor
     */
    500: Error;
};

export type GetDashboardMetricsError = GetDashboardMetricsErrors[keyof GetDashboardMetricsErrors];

export type GetDashboardMetricsResponses = {
    /**
     * Métricas del sistema
     */
    200: DashboardMetrics;
};

export type GetDashboardMetricsResponse = GetDashboardMetricsResponses[keyof GetDashboardMetricsResponses];

export type GetDashboardActivityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/activity';
};

export type GetDashboardActivityErrors = {
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Error interno del servidor
     */
    500: Error;
};

export type GetDashboardActivityError = GetDashboardActivityErrors[keyof GetDashboardActivityErrors];

export type GetDashboardActivityResponses = {
    /**
     * Actividad reciente del sistema
     */
    200: DashboardActivity;
};

export type GetDashboardActivityResponse = GetDashboardActivityResponses[keyof GetDashboardActivityResponses];
