// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000/api' | (string & {});
};

export type CommandPayload = {
    /**
     * Entorno de despliegue
     */
    environment?: string;
    /**
     * Versión a desplegar
     */
    version?: string;
};

export type CommandMetadata = {
    /**
     * Origen del comando
     */
    source?: string;
    /**
     * ID de correlación
     */
    correlationId?: string;
};

export type CommandResultData = {
    /**
     * Mensaje del resultado
     */
    message?: string;
    /**
     * Salida del comando
     */
    output?: string;
};

export type CommandRequest = {
    /**
     * Nombre del comando a ejecutar
     */
    command: string;
    payload?: CommandPayload;
    metadata?: CommandMetadata;
};

export type CommandResponse = {
    /**
     * ID único del comando
     */
    id: string;
    /**
     * Estado actual del comando
     */
    status: 'pending' | 'processing' | 'completed' | 'failed';
    /**
     * Comando ejecutado
     */
    command: string;
    payload?: CommandPayload;
    metadata?: CommandMetadata;
    result?: CommandResultData;
    /**
     * Mensaje de error si falló
     */
    error?: string;
    /**
     * Timestamp de creación
     */
    createdAt: string;
    /**
     * Timestamp de completado
     */
    completedAt?: string;
};

export type CommandListResponse = {
    items?: Array<CommandResponse>;
    total?: number;
    limit?: number;
    offset?: number;
};

export type CommandResult = {
    /**
     * ID único del comando
     */
    id?: string;
    /**
     * Estado actual del comando
     */
    status?: 'pending' | 'processing' | 'completed' | 'failed';
    result?: CommandResultData;
    /**
     * Mensaje de error si falló
     */
    error?: string;
    /**
     * Timestamp de completado
     */
    completedAt?: string;
};

export type Error = {
    /**
     * Código de error
     */
    error: string;
    /**
     * Mensaje descriptivo
     */
    message: string;
    /**
     * Detalles adicionales
     */
    details?: {
        [key: string]: unknown;
    };
};

/**
 * Filtrar por estado
 */
export type Status = 'pending' | 'processing' | 'completed' | 'failed';

/**
 * Filtrar por fuente
 */
export type Source = string;

/**
 * Límite de resultados
 */
export type Limit = number;

/**
 * Offset de paginación
 */
export type Offset = number;

/**
 * ID del comando
 */
export type CommandId = string;

export type ListCommandsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filtrar por estado
         */
        status?: 'pending' | 'processing' | 'completed' | 'failed';
        /**
         * Filtrar por fuente
         */
        source?: string;
        /**
         * Límite de resultados
         */
        limit?: number;
        /**
         * Offset de paginación
         */
        offset?: number;
    };
    url: '/commands';
};

export type ListCommandsErrors = {
    /**
     * No autorizado
     */
    401: Error;
};

export type ListCommandsError = ListCommandsErrors[keyof ListCommandsErrors];

export type ListCommandsResponses = {
    /**
     * Lista de comandos
     */
    200: CommandListResponse;
};

export type ListCommandsResponse = ListCommandsResponses[keyof ListCommandsResponses];

export type ExecuteCommandData = {
    body: CommandRequest;
    path?: never;
    query?: never;
    url: '/commands';
};

export type ExecuteCommandErrors = {
    /**
     * Solicitud inválida
     */
    400: Error;
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Demasiadas solicitudes
     */
    429: Error;
    /**
     * Error interno del servidor
     */
    500: Error;
};

export type ExecuteCommandError = ExecuteCommandErrors[keyof ExecuteCommandErrors];

export type ExecuteCommandResponses = {
    /**
     * Comando aceptado para procesamiento
     */
    202: CommandResponse;
};

export type ExecuteCommandResponse = ExecuteCommandResponses[keyof ExecuteCommandResponses];

export type GetCommandData = {
    body?: never;
    path: {
        /**
         * ID del comando
         */
        id: string;
    };
    query?: never;
    url: '/commands/{id}';
};

export type GetCommandErrors = {
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Recurso no encontrado
     */
    404: Error;
};

export type GetCommandError = GetCommandErrors[keyof GetCommandErrors];

export type GetCommandResponses = {
    /**
     * Estado del comando
     */
    200: CommandResponse;
};

export type GetCommandResponse = GetCommandResponses[keyof GetCommandResponses];

export type GetCommandResultData = {
    body?: never;
    path: {
        /**
         * ID del comando
         */
        id: string;
    };
    query?: never;
    url: '/commands/{id}/result';
};

export type GetCommandResultErrors = {
    /**
     * No autorizado
     */
    401: Error;
    /**
     * Recurso no encontrado
     */
    404: Error;
};

export type GetCommandResultError = GetCommandResultErrors[keyof GetCommandResultErrors];

export type GetCommandResultResponses = {
    /**
     * Resultado del comando
     */
    200: CommandResult;
};

export type GetCommandResultResponse = GetCommandResultResponses[keyof GetCommandResultResponses];
